#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akhil.github.io" # the base hostname & protocol for your site, e.g. http://example.com

title: Akhil Abraham George | akhilgeorge.com
description: "Hello, my name is Akhil Abraham George. I am a Blogger and SAP Consultant based in Kerala, India. This is my digital space on the Interwebs where I share insights on Enterprise Tech, Software Development, and Innovation."
author: Akhil Abraham George
email: mail@akhilgeorge.com
github:
  username: akhilgeo
social:
  name: Akhil Abraham George
  links:
    - https://linkedin.com/in/akhilgeorge
    - https://facebook.com/akhilgeo
    - https://instagram.com/akhilgeo
    - https://github.com/akhilgeo


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-seo-tag

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  style: compressed
